#!/bin/bash
path=$(cd `dirname $0`; pwd)
source ${path}/db_conf
day=`date '+%Y%m%d' -d '+1 days'`
mysql -h${source_host} -u${source_user} -p${source_pwd} admin -e "
CREATE TABLE \`log_login_${day}\` (
  \`id\` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  \`appid\` int(11) unsigned NOT NULL DEFAULT '100000' COMMENT '应用ID',
  \`cid\` bigint(20) DEFAULT '0' COMMENT '渠道ID',
  \`refer\` varchar(64) CHARACTER SET utf8 DEFAULT '' COMMENT '渠道位置',
  \`duid\` char(32) CHARACTER SET utf8 DEFAULT '' COMMENT '设备序号',
  \`uid\` bigint(20) DEFAULT '0',
  \`mac\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '设备MAC地址',
  \`client_id\` varchar(64) DEFAULT '',
  \`install\` tinyint(1) DEFAULT '0' COMMENT '1:首次安装或卸载重装 ，0是普通',
  \`utype\` tinyint(1) DEFAULT '0' COMMENT '1:注册 ，0是登录',
  \`version\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '游戏版本号',
  \`resolution\` varchar(12) CHARACTER SET utf8 DEFAULT '' COMMENT '分辨率(1024x768)',
  \`mod\` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1为模拟器',
  \`model\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '型号',
  \`os\` tinyint(1) NOT NULL DEFAULT '1' COMMENT '系统',
  \`sysver\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '系统版本',
  \`brand\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '设备厂商',
  \`pkgid\` varchar(64) CHARACTER SET utf8 DEFAULT '' COMMENT '底层包名',
  \`ntype\` varchar(8) CHARACTER SET utf8 DEFAULT '' COMMENT '网络类型(Network)',
  \`nname\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '网络名称',
  \`ip\` varchar(15) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '客户端IP',
  \`continent\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '大洲',
  \`country\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '国家',
  \`province\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '省份',
  \`city\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '城市',
  \`ymd\` int(8) NOT NULL COMMENT '年月日',
  \`h\` int(10) DEFAULT '0' COMMENT '年月日小时(2015070815)',
  \`rdate\` int(11) NOT NULL DEFAULT '0' COMMENT '注册日期',
  \`rhour\` int(11) NOT NULL DEFAULT '0' COMMENT '注册小时',
  \`atime\` int(11) DEFAULT '0' COMMENT '请求时间',
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`duid\` (\`duid\`) USING BTREE,
  KEY \`ymd\` (\`ymd\`,\`appid\`,\`cid\`,\`refer\`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='登录日志表';
CREATE TABLE \`log_active_${day}\` (
  \`id\` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  \`appid\` int(11) unsigned NOT NULL DEFAULT '100000' COMMENT '应用ID',
  \`cid\` bigint(20) DEFAULT '0' COMMENT '渠道ID',
  \`refer\` varchar(64) CHARACTER SET utf8 DEFAULT '' COMMENT '渠道位置',
  \`duid\` char(32) CHARACTER SET utf8 DEFAULT '' COMMENT '设备序号',
  \`uid\` bigint(20) DEFAULT '0',
  \`mac\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '设备MAC地址',
  \`client_id\` varchar(64) DEFAULT '',
  \`install\` tinyint(2) DEFAULT '0' COMMENT '1:首次安装或卸载重装 ，0是普通',
  \`version\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '游戏版本号',
  \`resolution\` varchar(12) CHARACTER SET utf8 DEFAULT '' COMMENT '分辨率(1024x768)',
  \`mod\` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1为模拟器',
  \`model\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '型号',
  \`os\` tinyint(1) NOT NULL DEFAULT '1' COMMENT '系统',
  \`sysver\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '系统版本',
  \`brand\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '设备厂商',
  \`pkgid\` varchar(64) CHARACTER SET utf8 DEFAULT '' COMMENT '底层包名',
  \`ntype\` varchar(8) CHARACTER SET utf8 DEFAULT '' COMMENT '网络类型(Network)',
  \`nname\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '网络名称',
  \`ip\` varchar(15) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '客户端IP',
  \`continent\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '大洲',
  \`country\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '国家',
  \`province\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '省份',
  \`city\` varchar(32) CHARACTER SET utf8 DEFAULT '' COMMENT '城市',
  \`ymd\` int(8) NOT NULL COMMENT '年月日',
  \`h\` int(10) DEFAULT '0' COMMENT '年月日小时(2015070815)',
  \`atime\` int(11) DEFAULT '0' COMMENT '请求时间',
  PRIMARY KEY (\`id\`),
  KEY \`duid\` (\`duid\`) USING BTREE,
  KEY \`ymd\` (\`ymd\`,\`appid\`,\`cid\`,\`refer\`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='登录日志表';"